RobertLuptonTheGood/eups

python/eups/Eups.py
python/eups/db/ChainFile.py
python/eups/db/VersionFile.py
python/eups/lock.py
python/eups/stack/ProductStack.py
python/eups/tags.py
python/eups/utils.py

Hi, 
By default eups fails on platforms where getpwuid doesn't work.
```
Traceback (most recent call last):
File "/global/homes/k/koposov/lsst92new/Linux64/obs_sdss/9.0+11/bin/processCcdSdss.py", line 23, in <module>
from lsst.obs.sdss.processCcdSdss import ProcessCcdSdssTask
File "/global/homes/k/koposov/lsst92new/Linux64/obs_sdss/9.0+11/python/lsst/obs/sdss/__init__.py", line 23, in <module>  
from sdssMapper import *
File "/global/homes/k/koposov/lsst92new/Linux64/obs_sdss/9.0+11/python/lsst/obs/sdss/sdssMapper.py", line 25, in <module>
from lsst.daf.butlerUtils import CameraMapper, exposureFromImage
File "/global/homes/k/koposov/lsst92new/Linux64/daf_butlerUtils/9.0+8/python/lsst/daf/butlerUtils/__init__.py", line 27, in <module>
from cameraMapper import *
File …
```

ensure that eups is working when getpwuid is not (e.g. on NERSC hopper)

---

lib/eupspkg.sh
python/eups/distrib/eupspkg.py

Instead of looking for an environment variable (which is hard to set) or
for the lack of files in the root directory, look for an explicit
".tap_package" file (in addition to looking for the "upstream"
directory).
This allows packages to contain other files like "README.md", providing a place to document how the external dependency was packaged, what patches were necessary, etc.

Improve TaP package detection.

---

bin/pkgautoversion
lib/bunit.sh

As stated in the original problem description, this change will, for commits on master only:
> provide a number that is derived from the most recent tag, sorts properly almost all the time, and is still traceable back to the original git commit
as opposed to using just "master-g{SHA}".
This PR also fixes minor bugs in the unit testing framework and unit tests.

eupspkg-generated versions on master are referenced to tags (LSST DM-2169)

---

python/eups/distrib/Distrib.py

The table file expansion respects 'force', and it's sometimes
helpful to get you out of a jam.

distrib: pass force down to table file expansion

---

python/eups/Eups.py
python/eups/db/ChainFile.py
python/eups/db/Database.py
python/eups/table.py
python/eups/utils.py

A series of performance optimizations for large installations (thousands of products), identified through profiling.
Together with related optimizations in sconsUtils, speeds up the product builds on lsst-dev by 1.5x-2.5x, depending on the product. E.g.:
Before:
```
ndarray: master-g7408a83a3a+4 ................................................ok (138.8 sec).
daf_persistence: 10.0+23 ......................................................ok (124.6 sec).
```
After:
```
ndarray: master-g7408a83a3a+5 .......................ok (87.5 sec).
daf_persistence: 10.0+23 ....................ok (55.2 sec).
```

Performance optimizations for large product stacks

---

lib/eupspkg.sh

Otherwise, when eupspkg is run in dev mode (with -e), the builds (which occur in _eupspkg/source) will still be looking in the original directory for files they have created (e.g., libraries).

lib/eupspkg.sh: run 'setup -j -r .' after chdir to _eupspkg/source

---

lib/eupspkg.sh

Adds ''--prefix="' after --home addition to suppress any previous prefix to fixes #49 
Note that there is no test case that reproduces the original problem (triggered by distutils.cfg in Homebrew).  I tested that I can install packages now.
python tests/testAll.py 
fails in the same tests before and after this change.

Add blank '--prefix=' option to protect '--home' specification to fix #49

---

bin/pkgautoversion

`bin/pkgautoversion` is the utility that tries to compute a reasonably-looking version from the git information. It can take an argument -- `REF` -- that it may use as a hint when it's constructing a version (e.g., if there are no annotated tags defined at all, then it will construct the version of the form `<REF>-g<SHA1>`).
Before this PR, `pkgautoversion` would check if `REF` was an annotated tag. If it was, it would return `REF` as the version. This worked as expected, as long as one followed a convention to use annotated tags for (numerical) version only (e.g., `10.1`, `10.1.2`, etc.).
The introduction of weekly tags of the form of `w.2015.33`, etc, changed the convention. That lead to many packages having a version such as `w.2015.33`, if the stack was built with `lsstsw` using a …

pkgautoversion: only match conforming tags passed via the command line

---

python/eups/distrib/server.py

Resolves this error message when setting `EUPS_PKGROOT` to a HTTPS URL.
eups distrib: Transport for file not recognized: ...

add https support to eups.distrib.server.WebTransporter

---

python/eups/Product.py
python/eups/app.py
python/eups/stack/ProductStack.py
python/eups/utils.py

Move back to the C implementation of pickle as it was used in 1.5.10 and fall back to `pickle` in python 3 or where the C implementation is not available.
Fixes #59

Use the C implementation of pickle in python 2

---

python/eups/tags.py
tests/testApp.py
tests/testCmd.py
tests/testDeprecated.py
tests/testEups.py

The new failures were due to the replacement of `cStringIO.StringIO` with `io.StringIO` -- in Python 2.7, the former expects `str`, while the latter expects `unicode`. I've fixed it by importing `cStringIO` in 2 and `io` in 3. Should fix #55 (I now reproduce the same failures as before the py3 compatibility patchset :) ).
@migueldvb, could you test if it breaks Python 3 compatibility?

Fix tests broken by py3 updates

---

lib/eupspkg.sh

Two key changes:
* Limit the autodetected number of parallel build jobs to 32. The user can still override it with `EUPSPKG_NJOBS`
* Attempt to up the number of processes (`ulimit -Su`) all the way to the hard limit.
See the related issue #58 for more discussion and the motivation for these fixes.

Make eupspkg more robust on machines with numerous cores

---

python/eups/db/ChainFile.py
python/eups/db/Database.py
python/eups/db/VersionFile.py
python/eups/distrib/Distrib.py
python/eups/distrib/DistribFactory.py
python/eups/distrib/Repositories.py
python/eups/distrib/Repository.py
python/eups/distrib/builder.py
python/eups/distrib/eupspkg.py
python/eups/distrib/pacman.py
python/eups/distrib/server.py
python/eups/distrib/tarball.py

This pull request goes a long way to fixing issue https://github.com/RobertLuptonTheGood/eups/issues/72. It cleans up the db and distrib sub-packages of eups, including fixing a half dozen or so errors involving undefined variables.
It leaves one important bug unfixed:
server.py has the following incorrect bit of code:
for versName in (inVersion, "any") or fnmatch.fnmatch(inVersion, versName):
if versName in self._mapping[flavor][inProduct]:
Without the `or fnmatch...` it makes sense. I have no idea what the bit involving the fnmatch is trying to do, so I don't know how to fix this. I have emailed several people, including Paul Price (who is credited with having been the last to edit the first of these lines).
Note: I suggest doing all of the following before merging this branch:
- Fix …

Fix much of issue 72

---

tests/testCommon.py
tests/testEups.py

Fixes the test failures from using the "current" tag, which is not a valid tag. It turns out that the tag "latest" is valid, so I changed all instances of "current" to "latest" in the two unit tests with failures. This leaves just one failure of `testDeclare`:
======================================================================
ERROR: testDeclare (testEups.EupsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
File "/Users/rowen/UW/LSST/eups_git/tests/testEups.py", line 369, in testDeclare
self.eups.undeclare("newprod")
File "/Users/rowen/UW/LSST/lsstsw/eups/git/python/eups/Eups.py", line 2742, in undeclare
(productName, "\" \"".join(versionList)))
EupsException: Product newprod has versions "1.0" "tag:beta"; please choose …

Fix more tests

---

python/eups/Eups.py
tests/testEups.py

Fix a problem introduced in 6e234b4. I think the intent of that commit was to allow re-declaration of a product's directory if it's been previously declared with a 'tag:<tagname>' version.  This allows for convenient usage such as:
```
setup -r . -t mytest
setup -r . -t mytest
```
where now the second copy is the one that's declared (and declared with a version of 'tag:mytest', and a tag 'mytest').  The way this was implemented, however, has had an odd side-effect of allowing things such as:
```
eups declare -r /stack/foo/1.2 foo 1.2 -t bar
eups declare -r /stack/foo/1.4 foo 1.2 -t bar
```
which would result in the following declared products:
```
foo, with version 1.2 in /stack/foo/1.2
foo, with version tag:bar in /stack/foo/1.4
```
(and, more broadly, redeclaration with _any_ change …

Fix 'eups declare' behavior, and the associated unit test

---

lib/eupspkg.sh
python/eups/distrib/eupspkg.py

Tested by running:
```
(
cd cfitsio &&
git reset --hard &&
git clean -f &&
source ../bin/setups.sh &&
touch blah &&
echo "TAP_PACKAGE=1" >> ups/eupspkg.cfg.sh &&
rm -rf _eupspkg &&
eupspkg -e fetch &&
eupspkg -e prep
)
```
and
```
(
cd cfitsio &&
git reset --hard &&
git clean -f &&
source ../bin/setups.sh &&
touch blah &&
touch .tap_package &&
rm -rf _eupspkg &&
eupspkg -e fetch &&
eupspkg -e prep
)
```
on a cloned `lsst/cfitsio` repository. (n.b., a unit test should be made for these, once there's some infrastructure to make that easy to do).

Reintroduce tap package variable

---

lib/eupspkg.sh
python/eups/distrib/eupspkg.py

Instead, use EUPSPKG_SCONSFLAGS to override SCONSFLAGS used 
by eupspkg when building products.
This avoids nasty surprises where a developer may have SCONSFLAGS set 
for every-day development work, but these then get picked up by eupspkg.
See https://jira.lsstcorp.org/browse/DM-1053?focusedCommentId=32844 for details.

eupspkg: Don't use SCONSFLAGS from the environment

---

Makefile.in
bin/Makefile
bin/eups.in
bin/eups_setup.in
bin/mksetup
ci/script.sh
configure
configure.ac
doc/Makefile
etc/Makefile
etc/bash_completion.d/Makefile
lib/Makefile
lib/eupspkg.sh
python/Makefile
python/eups/Eups.py
python/eups/distrib/eupspkg.py
python/eups/distrib/server.py
site/Makefile
tests/testCmd.py
tests/testEups.py
tests/testEupsIntegration/testDyldLibraryPath.sh
tests/testEupsIntegration/testSpaces.sh
ups/Makefile
ups/eups.table.in

Previous patches enabled spaces in paths for local setups. These patches enable spaces in paths for installation of EUPS.

Support spaces in paths for EUPS installation

---

python/eups/distrib/server.py

It can be confusing to report the "Failed to contact URL" message
without context as in some cases wget and curl can work fine
but urllib complains. Providing the reason may help.

Supply the reason for URL failure

---

python/eups/Product.py

The deprecation message in its current form makes no obvious
statement as to why the API was being used or where it was being
misused.
With this commit it now reports the file, line number and function
of the caller routine and gives the reason for triggering the
deprecation message.

Enhance content of the deprecation message

---

python/eups/Eups.py
python/eups/Product.py
python/eups/app.py
python/eups/cmd.py
python/eups/db/Database.py
python/eups/db/VersionFile.py
python/eups/distrib/Repositories.py
python/eups/distrib/Repository.py
python/eups/distrib/pacman.py
python/eups/distrib/server.py
python/eups/hooks.py
python/eups/stack/ProductStack.py
python/eups/table.py
python/eups/tags.py
python/eups/utils.py

Sometimes we can end up with unicode strings if the database has been created on Python 3 but accessed on Python 2. This causes some strange behavior as many of the checks for strings were assuming only "str". To be consistent across versions those checks are now different on Python 2 and Python 3. On Python 3 `str` is the only option but on Python 2 the comparison is now with `basestring`.

Use a utility function to check for strings

---

Makefile.in

Due to the way perl was being used to parse the EUPS_PATH, any perl
variable sigils present in EUPS_PATH would result in incorrect path
generation for EUPS_DB. Eg.,
$ perl -e 'foreach $d (split(":","/foo@bar")) { print "$d/ups_db\n"}'
/foo/ups_db
This was particularly problematic when running under jenkins, as
`<path>/<name>@<n>` is used to isolate concurrent builds of the same job
on a single build slave.

fix Makefile EUPS_DB path generation

---

python/eups/Eups.py
python/eups/Uses.py

This seems to be necessary to use `eups remove` on Python 3.

Add missing cmp import for Python 3 (fix for #111)

---

python/eups/Product.py
tests/testProduct.py

I found these while looking for other places that may have race conditions while pickling. I think they aren't used anywhere, and look like a leftover from an abandoned experiment. They may be confusing to newcomers, who may be tempted to use them.

Remove unused Product.persist() and .unpersist() methods

---

python/eups/Eups.py
tests/testEups.py

The input to `zlib.crc32()` has to be raw bytes, not a string.
While the fix here seems clearly appropriate, I struggled to write a good test: `Eups.declare()` is long and complex, which makes it hard to unit test. Better suggestions welcome.

Resolve string encoding error on Python 3

---

python/eups/distrib/Distrib.py
python/eups/distrib/Repositories.py
python/eups/distrib/tarball.py

N.b. Theoretically this choice could be done per-product; this may be necessary to support manifest.remap files correctly.

Allow distrib servers to choose not to expand table files

---

lib/eupspkg.sh

This fixes a lot of complications with eupspkg builds:
* The builds no longer have a .git directory that can confuse
the build into thinking it's in a developer tree.
* The _build directory can be masked with .gitignore to make
it much clearer what is going on when "git status" is run.
* EUPS third party packages no longer trash the container
ups directory when untarred.
This feature can be enabled by setting TAP_USE_BUILD_DIR in the
eupspkg.cfg.sh file.
I have not done extensive tests with this but a simple package test worked fine.
@parejkoj and @jhoblitt might be interested.

Enable eupspkg to use a sub directory for the build

---

python/eups/lock.py

If a user has multiple stacks in `EUPS_PATH`, one or more of which are writable followed by at least one that is not writable, the failure to create a lock directory for a shared lock in the non-writable stack will wipe out any memory of successfully created locks in the writable stacks.  This means that the locks in the writable stacks never get cleaned up.  This change at least preserves the memory of the successfully created locks, although it doesn't try to lock any writable stacks after the non-writable one in `EUPS_PATH`.

Implement a partial locking fix.

---

python/eups/distrib/server.py

Very large packages were causing problems on modest-memory machines (which are unusable for building from source but not necessarily for running from binaries).

Download from Web in 1 MB chunks

---

lib/eupspkg.sh

Currently, `eups` was allowing python packages to install their own dependencies via `pypi` on-the-fly. This behavior creates unpredictable installations since any dependences should be declared explicitly in `eups` or installed by the user separately. 
This PR adds two extra options for python installations that force the code to error if a dependence is not found. Note that these options are present only for `setuptools`-based python packages. For old `distutils`-based ones, the current script worked fine. Thus I added a fallback to the old installation via bash's `||` operator.
A better solution might be to use `pip` to install the local python packages. In that case, you can simply run `pip install --no-deps .` to install a package in your current working dir. I'm happy to switch to …

BUG make sure python packages only install themselves

---

python/eups/app.py
python/eups/tags.py

A bit of an edge case as accidentally things worked if more than one product was declared.

Fix `eups list -s -d` to not print a product even if none are setup

---

lib/eupspkg.sh

I haven't fully tested this out with an `eupspkg` mediated built yet.

Make NJOBS check cgroups-aware

---

.github/workflows/ci.yaml
python/eups/distrib/eupspkg.py

It seems like pipes.quote was python 2 and has been deprecated implicitly in python 3 since shlex was created.

Use shlex.quote instead of deprecated pipes.quote
